Milestone9: Add Devise Authentication
Favourezeugwa/Blog-app pull request #11
Opened 2022-10-05 22:54 UTC by Favourezeugwa

## In this milestone I implemented;
- Removed current_user method in ApplicationController

- Can register a new user.
- User logs in with a combination of email and password.
- Hashed passwords stored in the database.
- Ask for confirmation of email.
- Can reset password.
- Modify the views in devise for registration and login

2022-10-05 23:23 UTC, rloterh requested changes
Hi Team, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Devise gem properly added


## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷
<br><br>
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-05 23:23 UTC, rloterh commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
- [ ] As we want (new) users to able to confirm their email kindly ensure that `confirmable` is enabled on this app.

2022-10-05 23:23 UTC, rloterh commented on app/views/devise/registrations/new.html.erb
> +
- [ ] As required by this module, kindly modify the views in devise for the registration and login to match the styling of the [provided wireframe(s)](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md). Kindly ensure that the form (inputs and buttons) stretches across the screen and is centered accordingly.

**Your login view:**
![image](https://user-images.githubusercontent.com/12745474/194180713-88faa04c-07fc-4be5-80df-ef731c1f08e5.png)

**Wireframe login view:**
![image](https://user-images.githubusercontent.com/12745474/192667669-04020765-a648-4c50-ab45-7d68eda203e7.png)

2022-10-06 13:08 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @Favourezeugwa**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- The application allows for registering a new user.✔️  
- A user can log in with a combination of email and password.✔️  
- The application asks for confirmation of email  🥇 
- A user can reset the password in the application, keep rocking :rocket: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 13:52 UTC, merged